
import jon from "../../Img/jon.jpg";
import tinymce from "../../Img/tinymce.jpg";
import tinymcecool from "../../Img/tiny-cool.jpg";
import jesperWizard from "../../Img/jesperWizard.jpg";
import tp1crown from "../../Img/tp1crown.png";
import quire from "../../Img/quire.png";
import gold from "../../Img/gold.jpg";

export const CardsArray = [
  {
    name: "Jesper 1",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 75,
    atk: 900,
    def: 500,
    hp: 100,
    id: "jesper-one",
    value: 0,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper 2",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 75,
    atk: 900,
    def: 500,
    hp: 100,
    id: "jesper-two",
    value: 1,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper 3",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 75,
    atk: 900,
    def: 500,
    hp: 100,
    id: "jesper-three",
    value: 2,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper 4",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 75,
    atk: 1050,
    def: 500,
    hp: 100,
    id: "jesper-four",
    value: 3,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper 5",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 75,
    atk: 1050,
    def: 500,
    hp: 100,
    id: "jesper-five",
    value: 26,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper 6",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 75,
    atk: 1000,
    def: 500,
    hp: 100,
    id: "jesper-six",
    value: 27,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper 7",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 75,
    atk: 1000,
    def: 500,
    hp: 100,
    id: "jesper-seven",
    value: 28,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-one",
    value: 4,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-two",
    value: 5,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-three",
    value: 6,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-four",
    value: 7,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-five",
    value: 23,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-six",
    value: 24,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-seven",
    value: 25,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  }
  /* {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 75,
    id: "tiny-one",
    value: 8,
    descText:
      "Heal 50hp to every card on your board and deal 20 dmg to random opponent.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 75,
    id: "tiny-two",
    descText:
      "Heal 50hp to every card on your board and deal 20 dmg to random opponent.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 75,
    id: "tiny-three",
    value: 9,
    descText:
      "Heal 50hp to every card on your board and deal 20 dmg to random opponent.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 75,
    id: "tiny-four",
    value: 10,
    descText:
      "Heal 50hp to every card on your board and deal 20 dmg to random opponent.",
  },
  {
    name: "Tiny MC Daddy ",
    img: tinymcecool,
    type: "spell",
    cost: 75,
    id: "tiny-mc-one",
    value: 11,
    descText: "Dissables all enemy cards on the board for the next round",
  },
  {
    name: "Tiny MC Daddy ",
    img: tinymcecool,
    type: "spell",
    cost: 75,
    id: "tiny-mc-two",
    value: 12,
    descText: "Dissables all enemy cards on the board for the next round",
  },
  {
    name: "Tiny MC Daddy ",
    img: tinymcecool,
    type: "spell",
    cost: 75,
    id: "tiny-mc-three",
    value: 13,
    descText: "Dissables all enemy cards on the board for the next round",
  },
  {
    name: "Tiny MC Daddy ",
    img: tinymcecool,
    type: "spell",
    cost: 75,
    id: "tiny-mc-four",
    value: 14,
    descText: "Dissables all enemy cards on the board for the next round",
  },
  {
    name: "TP1",
    img: tp1crown,
    type: "spell",
    cost: 50,
    id: "tp1-one",
    value: 15,
    descText:
      "Give one of your cards the title “scrum-master” and give it +50atk",
  },
  {
    name: "TP1",
    img: tp1crown,
    type: "spell",
    cost: 50,
    id: "tp1-two",
    value: 16,
    descText:
      "Give one of your cards the title “scrum-master” and give it +50atk",
  },
  {
    name: "TP1",
    img: tp1crown,
    type: "spell",
    cost: 50,
    id: "tp1-three",
    value: 17,
    descText:
      "Give one of your cards the title “scrum-master” and give it +50atk",
  },
  {
    name: "Quire",
    img: quire,
    type: "spell",
    cost: 25,
    id: "quire-one",
    value: 18,
    descText:
      "Draw one card",
  },
  {
    name: "Quire",
    img: quire,
    type: "spell",
    cost: 25,
    id: "quire-two",
    value: 19,
    descText:
      "Draw one card",
  },
  {
    name: "Quire",
    img: quire,
    type: "spell",
    cost: 25,
    id: "quire-three",
    value: 20,
    descText:
      "Draw one card",
  },
  {
    name: "Money Making Idea",
    img: gold,
    type: "spell",
    cost: 50,
    id: "money-one",
    value: 21,
    descText:
      "Get 150 gold",
  },
  {
    name: "Money Making Idea",
    img: gold,
    type: "spell",
    cost: 50,
    id: "money-two",
    value: 22,
    descText:
      "Get 150 gold",
  }, */
];
