import React from "react";
import jesper from "../../Img/jesper.jpg";
import jon from "../../Img/jon.jpg";
import tinymce from "../../Img/tinymce.jpg";

export const CardsArray = [
  {
    name: "Jesper",
    img: jesper,
    type: "Spellcaster",
    cost: 75,
    atk: 900,
    def: 500,
    hp: 100,
    id: "jesper-one",
    value: 0,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper",
    img: jesper,
    type: "Spellcaster",
    cost: 75,
    atk: 900,
    def: 500,
    hp: 100,
    id: "jesper-two",
    value: 1,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper",
    img: jesper,
    type: "Spellcaster",
    cost: 75,
    atk: 900,
    def: 500,
    hp: 100,
    id: "jesper-three",
    value: 2,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jesper",
    img: jesper,
    type: "Spellcaster",
    cost: 75,
    atk: 900,
    def: 500,
    hp: 100,
    id: "jesper-four",
    value: 3,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 200,
    hp: 100,
    id: "jon-one",
    value: 4,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 200,
    hp: 100,
    id: "jon-two",
    value: 5,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 200,
    hp: 100,
    id: "jon-three",
    value: 6,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 200,
    hp: 100,
    id: "jon-four",
    value: 7,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 75,
    id: "tiny-one",
    value: 8,
    descText:
      "Heal 50hp to every card on your board and deal 20 dmg to random opponent.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 75,
    id: "tiny-two",
    descText:
      "Heal 50hp to every card on your board and deal 20 dmg to random opponent.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 75,
    id: "tiny-three",
    value: 9,
    descText:
      "Heal 50hp to every card on your board and deal 20 dmg to random opponent.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 75,
    id: "tiny-four",
    value: 10,
    descText:
      "Heal 50hp to every card on your board and deal 20 dmg to random opponent.",
  },
];
