
import jon from "../../Img/jon.jpg";
import tinymce from "../../Img/tinymce.jpg";
import tinymcecool from "../../Img/tiny-cool.jpg";
import jesperWizard from "../../Img/jesperWizard.jpg";
import jesper from "../../Img/jesper.jpg";
import tp1crown from "../../Img/tp1crown.png";
import quire from "../../Img/quire.png";
import gold from "../../Img/gold.jpg";
import kristian from "../../Img/juice-ghost.png";
import karlSexyman from "../../Img/karl-sexyman.png"
import FancyHarmonica from "../../Img/Fancy-Harmonica.png"
import MariachiBand from "../../Img/mariachi-band.png"

export const CardsArray = [
  {
    name: "Wizard",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 50,
    atk: 900,
    def: 600,
    hp: 100,
    id: "wizard-one",
    value: 0,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Wizard",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 50,
    atk: 900,
    def: 600,
    hp: 100,
    id: "wizard-two",
    value: 1,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Wizard",
    img: jesperWizard,
    type: "Spellcaster",
    cost: 50,
    atk: 900,
    def: 600,
    hp: 100,
    id: "wizard-three",
    value: 2,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-one",
    value: 3,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-two",
    value: 4,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-three",
    value: 5,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-four",
    value: 6,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-five",
    value: 7,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-six",
    value: 8,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Warrior",
    cost: 75,
    atk: 1200,
    def: 1000,
    hp: 100,
    id: "jon-seven",
    value: 9,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Mysterious Sexy Man",
    img: karlSexyman,
    type: "Seducer",
    cost: 100,
    atk: 2000,
    def: 1500,
    hp: 100,
    id: "karl-one",
    value: 10,
    descText: "This is the mysterious Sexy man once found as the winner of 'world sexiest man alive' in forbes, GQ and many other magazines.",
  },
  {
    name: "Mysterious Sexy Man",
    img: karlSexyman,
    type: "Seducer",
    cost: 100,
    atk: 2000,
    def: 1500,
    hp: 100,
    id: "karl-one",
    value: 11,
    descText: "This is the mysterious Sexy man once found as the winner of 'world sexiest man alive' in forbes, GQ and many other magazines.",
  },
  {
    name: "Mysterious Sexy Man",
    img: karlSexyman,
    type: "Seducer",
    cost: 100,
    atk: 2000,
    def: 1500,
    hp: 100,
    id: "karl-two",
    value: 12,
    descText: "This is the mysterious Sexy man once found as the winner of 'world sexiest man alive' in forbes, GQ and many other magazines.",
  },
  {
    name: "Mysterious Sexy Man",
    img: karlSexyman,
    type: "Seducer",
    cost: 100,
    atk: 2000,
    def: 1500,
    hp: 100,
    id: "karl-three",
    value: 13,
    descText: "This is the mysterious Sexy man once found as the winner of 'world sexiest man alive' in forbes, GQ and many other magazines.",
  },
  {
    name: "Juice Ghost",
    img: kristian,
    type: "King",
    cost: 300,
    atk: 5000,
    def: 5000,
    hp: 100,
    id: "juice-one",
    value: 14,
    descText: "The Notorious JucieGhost. Hide you family, hide your friends. Everythin you know and love can and WILL be gone.",
  },
  {
    name: "Juice Ghost",
    img: kristian,
    type: "King",
    cost: 300,
    atk: 5000,
    def: 5000,
    hp: 100,
    id: "juice-two",
    value: 15,
    descText: "The Notorious JucieGhost. Hide you family, hide your friends. Everythin you know and love can and WILL be gone.",
  },
  {
    name: "Juice Ghost",
    img: kristian,
    type: "King",
    cost: 300,
    atk: 5000,
    def: 5000,
    hp: 100,
    id: "juice-three",
    value: 16,
    descText: "The Notorious JucieGhost. Hide you family, hide your friends. Everythin you know and love can and WILL be gone.",
  },
  {
    name: "Programmer",
    img: jesper,
    type: "Programmer",
    cost: 50,
    atk: 1500,
    def: 2000,
    hp: 100,
    id: "programmer-one",
    value: 17,
    descText: "He will use code to defeat his enemies, if(enemy exist){destroy it}...",
  },
  {
    name: "Programmer",
    img: jesper,
    type: "Programmer",
    cost: 50,
    atk: 1500,
    def: 2000,
    hp: 100,
    id: "programmer-two",
    value: 18,
    descText: "He will use code to defeat his enemies, if(enemy exist){destroy it}...",
  },
  {
    name: "Harmonica",
    img: FancyHarmonica,
    type: "spell",
    cost: 200,
    id: "harmonica-one",
    value: 19,
    descText: "It's 8am. Your about to meet with the buyer. All of a sudden Anton plays the harmonica and all enemys are silienced for the next round.",
  },
  {
    name: "Harmonica",
    img: FancyHarmonica,
    type: "spell",
    cost: 200,
    id: "harmonica-two",
    value: 20,
    descText: "It's 8am. Your about to meet with the buyer. All of a sudden Anton plays the harmonica and all enemys are silienced for the next round.",
  },
  {
    name: "Harmonica",
    img: FancyHarmonica,
    type: "spell",
    cost: 200,
    id: "harmonica-three",
    value: 21,
    descText: "It's 8am. Your about to meet with the buyer. All of a sudden Anton plays the harmonica and all enemys are silienced for the next round.",
  },
  {
    name: "The Almighty Mariachi Group",
    img: MariachiBand,
    type: "Mariachi Group",
    atk: 350,
    def: 5500,
    hp: 100,
    cost: 500,
    id: "mariachi-one",
    value: 21,
    descText: "This card summuons the almighty Mariachi Group that decends from the Gutenberg era. Wait no more becuse now stuff is truly about to go down.",
  },
  {
    name: "The Almighty Mariachi Group",
    img: MariachiBand,
    type: "Mariachi Group",
    atk: 350,
    def: 5500,
    hp: 100,
    cost: 500,
    id: "mariachi-two",
    value: 22,
    descText: "This card summuons the almighty Mariachi Group that decends from the Gutenberg era. Wait no more becuse now stuff is truly about to go down.",
  },
  {
    name: "The Almighty Mariachi Group",
    img: MariachiBand,
    type: "Mariachi Group",
    atk: 350,
    def: 5500,
    hp: 100,
    cost: 500,
    id: "mariachi-three",
    value: 23,
    descText: "This card summuons the almighty Mariachi Group that decends from the Gutenberg era. Wait no more becuse now stuff is truly about to go down.",
  },
  {
    name: "The Almighty Mariachi Group",
    img: MariachiBand,
    type: "Mariachi Group",
    atk: 350,
    def: 5500,
    hp: 100,
    cost: 500,
    id: "mariachi-four",
    value: 24,
    descText: "This card summuons the almighty Mariachi Group that decends from the Gutenberg era. Wait no more becuse now stuff is truly about to go down.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 70,
    id: "tiny-one",
    value: 25,
    descText:
      "Heal 50hp to every friendly card on your board and give +100 def.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 70,
    id: "tiny-two",
    value: 26,
    descText:
      "Heal 50hp to every friendly card on your board and give +100 def.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 70,
    id: "tiny-three",
    value: 27,
    descText:
      "Heal 50hp to every friendly card on your board and give +100 def.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "spell",
    cost: 70,
    id: "tiny-four",
    value: 28,
    descText:
      "Heal 50hp to every friendly card on your board and give +100 def.",
  },
  {
      name: "TP1",
      img: tp1crown,
      type: "spell",
      cost: 50,
      id: "tp1-one",
      value: 29,
      descText:
        "Give one of your cards the title “scrum-master” and give it +100atk",
    },
    {
      name: "TP1",
      img: tp1crown,
      type: "spell",
      cost: 50,
      id: "tp1-two",
      value: 30,
      descText:
        "Give one of your cards the title “scrum-master” and give it +100atk",
    },
    {
      name: "TP1",
      img: tp1crown,
      type: "spell",
      cost: 50,
      id: "tp1-three",
      value: 31,
      descText:
        "Give one of your cards the title “scrum-master” and give it +100atk",
    },
  // {
  //   name: "Tiny MC Daddy ",
  //   img: tinymcecool,
  //   type: "spell",
  //   cost: 75,
  //   id: "tiny-mc-one",
  //   value: 11,
  //   descText: "Dissables all enemy cards on the board for the next round",
  // },
  // {
  //   name: "Tiny MC Daddy ",
  //   img: tinymcecool,
  //   type: "spell",
  //   cost: 75,
  //   id: "tiny-mc-two",
  //   value: 12,
  //   descText: "Dissables all enemy cards on the board for the next round",
  // },
  // {
  //   name: "Tiny MC Daddy ",
  //   img: tinymcecool,
  //   type: "spell",
  //   cost: 75,
  //   id: "tiny-mc-three",
  //   value: 13,
  //   descText: "Dissables all enemy cards on the board for the next round",
  // },
  // {
  //   name: "Tiny MC Daddy ",
  //   img: tinymcecool,
  //   type: "spell",
  //   cost: 75,
  //   id: "tiny-mc-four",
  //   value: 14,
  //   descText: "Dissables all enemy cards on the board for the next round",
  // },
  // 
  // {
  //   name: "Quire",
  //   img: quire,
  //   type: "spell",
  //   cost: 25,
  //   id: "quire-one",
  //   value: 18,
  //   descText:
  //     "Draw one card",
  // },
  // {
  //   name: "Quire",
  //   img: quire,
  //   type: "spell",
  //   cost: 25,
  //   id: "quire-two",
  //   value: 19,
  //   descText:
  //     "Draw one card",
  // },
  // {
  //   name: "Quire",
  //   img: quire,
  //   type: "spell",
  //   cost: 25,
  //   id: "quire-three",
  //   value: 20,
  //   descText:
  //     "Draw one card",
  // },
  // {
  //   name: "Money Making Idea",
  //   img: gold,
  //   type: "spell",
  //   cost: 0,
  //   id: "money-one",
  //   value: 21,
  //   descText:
  //     "Get 100 gold",
  // },
  // {
  //   name: "Money Making Idea",
  //   img: gold,
  //   type: "spell",
  //   cost: 0,
  //   id: "money-two",
  //   value: 22,
  //   descText:
  //     "Get 100 gold",
  // },
];
