import jon from "../../Img/jon.jpg";
import tinymce from "../../Img/tinymce.jpg";
import tinymcecool from "../../Img/tiny-cool.jpg";
import jesperWizard from "../../Img/jesperWizard.jpg";
import jesper from "../../Img/jesper.jpg";
import tp1crown from "../../Img/tp1crown.png";
import quire from "../../Img/quire.png";
import gold from "../../Img/gold.jpg";
import kristian from "../../Img/juice-ghost.png";
import karlSexyman from "../../Img/karl-sexyman.png";
import FancyHarmonica from "../../Img/Fancy-Harmonica.png";
import MariachiBand from "../../Img/mariachi-band.png";
import onur from "../../Img/onur.png";
import espressoHouse from "../../Img/espressoHouse.jpg";
import jonPlus from "../../Img/jonPlus.jpg";
import malware from "../../Img/malware.jpg";
import coffee from "../../Img/coffee.jpg";
import anton from "../../Img/anton.png";
import error from "../../Img/error.png";

export const OpponentCardArray = [
  {
    name: "Wizard",
    img: jesperWizard,
    type: "Spellcaster",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 500,
    hp: 100,
    id: "wizard-one",
    value: 0,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Wizard",
    img: jesperWizard,
    type: "Spellcaster",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 500,
    hp: 100,
    id: "wizard-two",
    value: 1,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Wizard",
    img: jesperWizard,
    type: "Spellcaster",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 500,
    hp: 100,
    id: "wizard-three",
    value: 2,
    descText: "Fearsome spellcaster! Known for its strength and cruelsome.",
  },
  {
    name: "Jon",
    img: jon,
    type: "Programmer",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 1000,
    hp: 100,
    id: "jon-one",
    value: 3,
    descText:
      "Fear not, Jon is here! Known for his expertis in taking long walks, he will leave no enemies standing",
  },
  {
    name: "Jon",
    img: jon,
    type: "Programmer",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 1000,
    hp: 100,
    id: "jon-two",
    value: 4,
    descText:
      "Fear not, Jon is here! Known for his expertis in taking long walks, he will leave no enemies standing",
  },
  {
    name: "Jon",
    img: jon,
    type: "Programmer",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 1000,
    hp: 100,
    id: "jon-three",
    value: 5,
    descText:
      "Fear not, Jon is here! Known for his expertis in taking long walks, he will leave no enemies standing",
  },
  {
    name: "Jon",
    img: jon,
    type: "Programmer",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 1000,
    hp: 100,
    id: "jon-four",
    value: 6,
    descText:
      "Fear not, Jon is here! Known for his expertis in taking long walks, he will leave no enemies standing",
  },
  {
    name: "Jon",
    img: jon,
    type: "Programmer",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 1000,
    hp: 100,
    id: "jon-five",
    value: 7,
    descText:
      "Fear not, Jon is here! Known for his expertis in taking long walks, he will leave no enemies standing",
  },
  {
    name: "Jon",
    img: jon,
    type: "Programmer",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 1000,
    hp: 100,
    id: "jon-six",
    value: 8,
    descText:
      "Fear not, Jon is here! Known for his expertis in taking long walks, he will leave no enemies standing",
  },
  {
    name: "Jon",
    img: jon,
    type: "Programmer",
    typeTwo: "character",
    cost: 50,
    atk: 200,
    def: 1000,
    hp: 100,
    id: "jon-seven",
    value: 9,
    descText:
      "Fear not, Jon is here! Known for his expertis in taking long walks, he will leave no enemies standing",
  },
  {
    name: "Mysterious Sexy Man",
    img: karlSexyman,
    type: "Seducer",
    typeTwo: "character",
    cost: 150,
    atk: 800,
    def: 1200,
    hp: 100,
    id: "karl-one",
    value: 10,
    descText:
      "This is the mysterious Sexy man once found as the winner of 'world sexiest man alive' in forbes, GQ and many other magazines.",
  },
  {
    name: "Mysterious Sexy Man",
    img: karlSexyman,
    type: "Seducer",
    typeTwo: "character",
    cost: 150,
    atk: 800,
    def: 1200,
    hp: 100,
    id: "karl-one",
    value: 11,
    descText:
      "This is the mysterious Sexy man once found as the winner of 'world sexiest man alive' in forbes, GQ and many other magazines.",
  },
  {
    name: "Mysterious Sexy Man",
    img: karlSexyman,
    type: "Seducer",
    typeTwo: "character",
    cost: 150,
    atk: 800,
    def: 1200,
    hp: 100,
    id: "karl-two",
    value: 12,
    descText:
      "This is the mysterious Sexy man once found as the winner of 'world sexiest man alive' in forbes, GQ and many other magazines.",
  },
  {
    name: "Mysterious Sexy Man",
    img: karlSexyman,
    type: "Seducer",
    typeTwo: "character",
    cost: 150,
    atk: 800,
    def: 1200,
    hp: 100,
    id: "karl-three",
    value: 13,
    descText:
      "This is the mysterious Sexy man once found as the winner of 'world sexiest man alive' in forbes, GQ and many other magazines.",
  },
  {
    name: "Juice Ghost",
    img: kristian,
    type: "King",
    typeTwo: "character",
    cost: 600,
    atk: 2000,
    def: 3500,
    hp: 100,
    id: "juice-one",
    value: 14,
    descText:
      "The Notorious JuiceGhost. Hide you family, hide your friends. Everythin you know and love can and WILL be gone.",
  },
  {
    name: "Juice Ghost",
    img: kristian,
    type: "King",
    typeTwo: "character",
    cost: 600,
    atk: 2000,
    def: 3500,
    hp: 100,
    id: "juice-two",
    value: 15,
    descText:
      "The Notorious JuiceGhost. Hide you family, hide your friends. Everythin you know and love can and WILL be gone.",
  },
  {
    name: "Juice Ghost",
    img: kristian,
    type: "King",
    typeTwo: "character",
    cost: 600,
    atk: 2000,
    def: 3500,
    hp: 100,
    id: "juice-three",
    value: 16,
    descText:
      "The Notorious JuiceGhost. Hide you family, hide your friends. Everythin you know and love can and WILL be gone.",
  },
  {
    name: "Jesper",
    img: jesper,
    type: "Programmer",
    typeTwo: "character",
    cost: 200,
    atk: 1050,
    def: 1200,
    hp: 100,
    id: "programmer-one",
    value: 17,
    descText:
      "He will use code to defeat his enemies, if(enemy exist){destroy it}...",
  },
  {
    name: "Jesper",
    img: jesper,
    type: "Programmer",
    typeTwo: "character",
    cost: 200,
    atk: 1050,
    def: 1200,
    hp: 100,
    id: "programmer-two",
    value: 18,
    descText:
      "He will use code to defeat his enemies, if(enemy exist){destroy it}...",
  },
  {
    name: "Harmonica",
    img: FancyHarmonica,
    type: "damage-spell",
    cost: 250,
    id: "harmonica-one",
    value: 19,
    descText:
      "It's 8am. Your about to meet with the buyer. All of a sudden Anton plays the harmonica and all enemys are silienced for the next round and damages all enemy card for 200.",
  },
  {
    name: "Harmonica",
    img: FancyHarmonica,
    type: "damage-spell",
    cost: 250,
    id: "harmonica-two",
    value: 20,
    descText:
      "It's 8am. Your about to meet with the buyer. All of a sudden Anton plays the harmonica and all enemys are silienced for the next round and damages all enemy card for 200.",
  },
  {
    name: "Harmonica",
    img: FancyHarmonica,
    type: "damage-spell",
    cost: 250,
    id: "harmonica-three",
    value: 21,
    descText:
      "It's 8am. Your about to meet with the buyer. All of a sudden Anton plays the harmonica and all enemys are silienced for the next round and damages all enemy card for 200.",
  },
  {
    name: "Gutenberg Mariachi",
    img: MariachiBand,
    type: "Mariachi Group",
    typeTwo: "character",
    atk: 200,
    def: 3500,
    hp: 100,
    cost: 350,
    id: "mariachi-one",
    value: 21,
    descText:
      "This card summuons the almighty Mariachi Group that decends from the Gutenberg era. Wait no more becuse now stuff is truly about to go down. This band deals 150 dmg to all opponents with its mighty music",
  },
  {
    name: "Gutenberg Mariachi",
    img: MariachiBand,
    type: "Mariachi Group",
    typeTwo: "character",
    atk: 200,
    def: 3500,
    hp: 100,
    cost: 350,
    id: "mariachi-two",
    value: 22,
    descText:
      "This card summons the almighty Mariachi Group that decends from the Gutenberg era. Wait no more becuse now stuff is truly about to go down. This band deals 150 dmg to all opponents with its mighty music",
  },
  {
    name: "Gutenberg Mariachi",
    img: MariachiBand,
    type: "Mariachi Group",
    typeTwo: "character",
    atk: 200,
    def: 3500,
    hp: 100,
    cost: 350,
    id: "mariachi-three",
    value: 23,
    descText:
      "This card summons the almighty Mariachi Group that decends from the Gutenberg era. Wait no more becuse now stuff is truly about to go down. This band deals 150 dmg to all opponents with its mighty music",
  },
  {
    name: "Gutenberg Mariachi",
    img: MariachiBand,
    type: "Mariachi Group",
    typeTwo: "character",
    atk: 200,
    def: 3500,
    hp: 100,
    cost: 350,
    id: "mariachi-four",
    value: 24,
    descText:
      "This card summons the almighty Mariachi Group that decends from the Gutenberg era. Wait no more becuse now stuff is truly about to go down. This band deals 150 dmg to all opponents with its mighty music",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "synergi-spell",
    cost: 70,
    id: "tiny-one",
    value: 25,
    descText:
      "Heal 50hp to every friendly card on your board and give +100 def.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "synergi-spell",
    cost: 70,
    id: "tiny-two",
    value: 26,
    descText:
      "Heal 50hp to every friendly card on your board and give +100 def.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "synergi-spell",
    cost: 70,
    id: "tiny-three",
    value: 27,
    descText:
      "Heal 50hp to every friendly card on your board and give +100 def.",
  },
  {
    name: "TinyMCE",
    img: tinymce,
    type: "synergi-spell",
    cost: 70,
    id: "tiny-four",
    value: 28,
    descText:
      "Heal 50hp to every friendly card on your board and give +100 def.",
  },
  {
    name: "TP1",
    img: tp1crown,
    type: "synergi-spell",
    cost: 50,
    id: "tp1-one",
    value: 29,
    descText:
      "Give one random card the title “scrum-master” and give it +100atk",
  },
  {
    name: "TP1",
    img: tp1crown,
    type: "synergi-spell",
    cost: 50,
    id: "tp1-two",
    value: 30,
    descText:
      "Give one random card the title “scrum-master” and give it +100atk",
  },
  {
    name: "TP1",
    img: tp1crown,
    type: "synergi-spell",
    cost: 50,
    id: "tp1-three",
    value: 31,
    descText:
      "Give one random card the title “scrum-master” and give it +100atk",
  },
  {
    name: "Quire",
    img: quire,
    type: "self-spell",
    cost: 25,
    id: "quire-one",
    value: 32,
    descText: "Draw one card",
  },
  {
    name: "Quire",
    img: quire,
    type: "self-spell",
    cost: 25,
    id: "quire-two",
    value: 33,
    descText: "Draw one card",
  },

  {
    name: "Money Making Idea",
    img: gold,
    type: "self-spell",
    cost: 0,
    id: "money-one",
    value: 34,
    descText: "Get 100 gold",
  },
  {
    name: "Money Making Idea",
    img: gold,
    type: "self-spell",
    cost: 0,
    id: "money-two",
    value: 35,
    descText: "Get 100 gold",
  },
  {
    name: "Tiny MC Daddy",
    img: tinymcecool,
    type: "damage-spell",
    cost: 100,
    id: "tiny-mc-one",
    value: 36,
    descText: "Dissables all enemy cards on the board for the next round",
  },
  {
    name: "Tiny MC Daddy",
    img: tinymcecool,
    type: "damage-spell",
    cost: 100,
    id: "tiny-mc-two",
    value: 37,
    descText: "Dissables all enemy cards on the board for the next round",
  },
  {
    name: "Tiny MC Daddy",
    img: tinymcecool,
    type: "damage-spell",
    cost: 100,
    id: "tiny-mc-three",
    value: 38,
    descText: "Dissables all enemy cards on the board for the next round",
  },
  {
    name: "Onur",
    img: onur,
    type: "Programmer",
    typeTwo: "character",
    atk: 800,
    def: 1500,
    hp: 100,
    cost: 250,
    id: "onur-one",
    value: 39,
    descText:
      "If the environment is “espresso house” this card gets +500 atk and +500 def",
  },
  {
    name: "Onur",
    img: onur,
    type: "Programmer",
    typeTwo: "character",
    atk: 800,
    def: 1500,
    hp: 100,
    cost: 250,
    id: "onur-two",
    value: 40,
    descText:
      "If the environment is “espresso house” this card gets +500 atk and +500 def",
  },
  {
    name: "Espresso House",
    img: espressoHouse,
    type: "self-spell",
    cost: 150,
    id: "house-one",
    value: 41,
    descText: "Change the environment to “Espresso House”",
  },
  {
    name: "Jon Level Two",
    img: jonPlus,
    type: "synergi-spell",
    cost: 200,
    id: "jonUpgrade-one",
    value: 42,
    descText:
      "Give every Jon on the battlefield, in your hand and deck, +500 atk and +300 def.",
  },
  {
    name: "Malware",
    img: malware,
    type: "self-spell",
    cost: 200,
    id: "malware-one",
    value: 43,
    descText:
      "This malware affects your opponent. Deal 100 dmg directly to your opponent.",
  },
  {
    name: "Malware",
    img: malware,
    type: "self-spell",
    cost: 200,
    id: "malware-two",
    value: 44,
    descText:
      "This malware affects your opponent. Deal 100 dmg directly to your opponent.",
  },
  {
    name: "Malware",
    img: malware,
    type: "self-spell",
    cost: 200,
    id: "malware-three",
    value: 45,
    descText:
      "This malware affects your opponent. Deal 100 dmg directly to your opponent.",
  },
  {
    name: "Coffee",
    img: coffee,
    type: "synergi-spell",
    cost: 100,
    id: "coffee-one",
    value: 46,
    descText:
      "Give every character on battlefield and in hand with type programmer +250 atk and +150 def",
  },
  {
    name: "Coffee",
    img: coffee,
    type: "synergi-spell",
    cost: 100,
    id: "coffee-two",
    value: 47,
    descText:
      "Give every character on battlefield and in hand with type programmer +250 atk and +150 def",
  },
  {
    name: "Coffee",
    img: coffee,
    type: "synergi-spell",
    cost: 100,
    id: "coffee-three",
    value: 48,
    descText:
      "Give every character on battlefield and in hand with type programmer +250 atk and +150 def",
  },
  {
    name: "Anton",
    img: anton,
    type: "Musician",
    typeTwo: "character",
    atk: 1000,
    def: 750,
    hp: 100,
    cost: 270,
    id: "anton-one",
    value: 49,
    descText:
      "Anton gets empowered by music, if harmonica has been played power up Anton and give this card +650 atk",
  },
  {
    name: "Anton",
    img: anton,
    type: "Musician",
    typeTwo: "character",
    atk: 1000,
    def: 750,
    hp: 100,
    cost: 270,
    id: "anton-two",
    value: 50,
    descText:
      "Anton gets empowered by music, if harmonica has been played power up Anton and give this card +650 atk",
  },
  {
    name: "Error",
    img: error,
    type: "damage-spell",
    cost: 300,
    id: "error-one",
    value: 51,
    descText: "An error! Throw a error on a random opponent and deal 600 dmg",
  },
  {
    name: "Error",
    img: error,
    type: "damage-spell",
    cost: 300,
    id: "error-two",
    value: 52,
    descText: "An error! Throw a error on a random opponent and deal 600 dmg",
  },
];
